version: '3.0'

services:
  grafana:
    container_name: 'example'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-10.4.2}
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:3000/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/example
      - ./provisioning:/etc/grafana/provisioning
